/* authoring/plurals.js — German plural forms for Course v2 (single source of truth).
 *
 * Plurals are German-only content (no locale alignment), so — unlike the four-language vocab T4s
 * in authoring/weeks/*.js — they live in one flat map here rather than inline on each word.
 *
 *   PLURALS   keyed by the EXACT singular string (with article) as it appears in a week's vocab;
 *             value is the plural form, always starting with the plural article "die ".
 *   NO_PLURAL noun-shaped vocab words that intentionally get NO plural card (mass/uncountable,
 *             abstract, plural-only, month names).
 *
 * scripts/gen-course.js validates this (every key resolves to a real vocab noun; every
 * noun-shaped vocab word is classified as either PLURALS or NO_PLURAL — the coverage gate) and
 * emits `const PLURALS` into data/v2/vocab.js. scripts/cutover-v2.js then ships it verbatim.
 * Add a new noun to a week's vocab ⇒ add it here too (or gen:course fails).
 */
module.exports = {
  PLURALS: {
    'das Land': 'die Länder',
    'die Sprache': 'die Sprachen',
    'die Familie': 'die Familien',
    'der Vater': 'die Väter',
    'die Mutter': 'die Mütter',
    'der Sohn': 'die Söhne',
    'die Tochter': 'die Töchter',
    'der Bruder': 'die Brüder',
    'die Schwester': 'die Schwestern',
    'das Kind': 'die Kinder',
    'das Brot': 'die Brote',
    'das Ei': 'die Eier',
    'der Fisch': 'die Fische',
    'der Apfel': 'die Äpfel',
    'der Supermarkt': 'die Supermärkte',
    'die Bäckerei': 'die Bäckereien',
    'der Markt': 'die Märkte',
    'der Preis': 'die Preise',
    'das Kilo': 'die Kilo',
    'die Flasche': 'die Flaschen',
    'der Saft': 'die Säfte',
    'der Kuchen': 'die Kuchen',
    'das Hobby': 'die Hobbys',
    'das Buch': 'die Bücher',
    'der Film': 'die Filme',
    'das Konzert': 'die Konzerte',
    'das Museum': 'die Museen',
    'der Park': 'die Parks',
    'das Haus': 'die Häuser',
    'die Wohnung': 'die Wohnungen',
    'das Zimmer': 'die Zimmer',
    'das Schlafzimmer': 'die Schlafzimmer',
    'das Wohnzimmer': 'die Wohnzimmer',
    'die Küche': 'die Küchen',
    'das Bad': 'die Bäder',
    'der Balkon': 'die Balkone',
    'der Flur': 'die Flure',
    'der Garten': 'die Gärten',
    'der Tisch': 'die Tische',
    'der Stuhl': 'die Stühle',
    'das Sofa': 'die Sofas',
    'der Sessel': 'die Sessel',
    'das Bett': 'die Betten',
    'der Schrank': 'die Schränke',
    'das Regal': 'die Regale',
    'der Teppich': 'die Teppiche',
    'die Lampe': 'die Lampen',
    'das Bild': 'die Bilder',
    'die Tür': 'die Türen',
    'das Fenster': 'die Fenster',
    'die Wand': 'die Wände',
    'die Uhr': 'die Uhren',
    'die Stunde': 'die Stunden',
    'die Minute': 'die Minuten',
    'die Woche': 'die Wochen',
    'der Monat': 'die Monate',
    'das Datum': 'die Daten',
    'der Tag': 'die Tage',
    'der Morgen': 'die Morgen',
    'der Vormittag': 'die Vormittage',
    'der Mittag': 'die Mittage',
    'der Nachmittag': 'die Nachmittage',
    'der Abend': 'die Abende',
    'die Nacht': 'die Nächte',
    'der Wecker': 'die Wecker',
    'die Dusche': 'die Duschen',
    'das Auto': 'die Autos',
    'der Bus': 'die Busse',
    'die U-Bahn': 'die U-Bahnen',
    'die S-Bahn': 'die S-Bahnen',
    'die Straßenbahn': 'die Straßenbahnen',
    'das Fahrrad': 'die Fahrräder',
    'der Zug': 'die Züge',
    'das Flugzeug': 'die Flugzeuge',
    'das Taxi': 'die Taxis',
    'die Haltestelle': 'die Haltestellen',
    'der Bahnhof': 'die Bahnhöfe',
    'der Flughafen': 'die Flughäfen',
    'die Fahrkarte': 'die Fahrkarten',
    'die Reise': 'die Reisen',
    'das Hotel': 'die Hotels',
    'der Koffer': 'die Koffer',
    'der Rucksack': 'die Rucksäcke',
    'der Weg': 'die Wege',
    'die Fahrt': 'die Fahrten',
    'der Fahrplan': 'die Fahrpläne',
    'der Ausgang': 'die Ausgänge',
    'der Eingang': 'die Eingänge',
    'die Verspätung': 'die Verspätungen',
    'die Stadt': 'die Städte',
    'das Dorf': 'die Dörfer',
    'die Straße': 'die Straßen',
    'der Platz': 'die Plätze',
    'die Kreuzung': 'die Kreuzungen',
    'die Ampel': 'die Ampeln',
    'die Brücke': 'die Brücken',
    'das Krankenhaus': 'die Krankenhäuser',
    'die Apotheke': 'die Apotheken',
    'die Bank': 'die Banken',
    'die Kirche': 'die Kirchen',
    'das Rathaus': 'die Rathäuser',
    'das Kino': 'die Kinos',
    'die Bibliothek': 'die Bibliotheken',
    'das Stadtzentrum': 'die Stadtzentren',
    'die Ecke': 'die Ecken',
    'der Körper': 'die Körper',
    'der Kopf': 'die Köpfe',
    'das Auge': 'die Augen',
    'das Ohr': 'die Ohren',
    'die Nase': 'die Nasen',
    'der Mund': 'die Münder',
    'der Zahn': 'die Zähne',
    'die Hand': 'die Hände',
    'der Arm': 'die Arme',
    'das Bein': 'die Beine',
    'der Fuß': 'die Füße',
    'der Bauch': 'die Bäuche',
    'der Rücken': 'die Rücken',
    'das Herz': 'die Herzen',
    'der Arzt': 'die Ärzte',
    'die Tablette': 'die Tabletten',
    'der Wind': 'die Winde',
    'die Wolke': 'die Wolken',
    'die Temperatur': 'die Temperaturen',
    'der Grad': 'die Grade',
    'die Biografie': 'die Biografien',
    'das Leben': 'die Leben',
    'der Beruf': 'die Berufe',
    'der Geburtstag': 'die Geburtstage',
    'das Geschenk': 'die Geschenke',
    'das Fest': 'die Feste',
    'der Feiertag': 'die Feiertage',
    'die Hochzeit': 'die Hochzeiten',
    'die Einladung': 'die Einladungen',
    'die Schule': 'die Schulen',
    'der Schüler': 'die Schüler',
    'der Lehrer': 'die Lehrer',
    'die Universität': 'die Universitäten',
    'der Student': 'die Studenten',
    'das Studium': 'die Studien',
    'das Fach': 'die Fächer',
    'die Note': 'die Noten',
    'die Prüfung': 'die Prüfungen',
    'der Job': 'die Jobs',
    'die Stelle': 'die Stellen',
    'der Chef': 'die Chefs',
    'der Kollege': 'die Kollegen',
    'das Gehalt': 'die Gehälter',
    'die Karriere': 'die Karrieren',
    'der Erfolg': 'die Erfolge',
    'der Lebenslauf': 'die Lebensläufe',
    'das Praktikum': 'die Praktika',
    'der Termin': 'die Termine',
    'das Formular': 'die Formulare',
    'der Ausweis': 'die Ausweise',
    'der Vertrag': 'die Verträge',
    'das Amt': 'die Ämter',
    'der Antrag': 'die Anträge',
    'die Unterschrift': 'die Unterschriften',
    'der Charakter': 'die Charaktere',
    'der Grund': 'die Gründe',
    'der Vorteil': 'die Vorteile',
    'der Nachteil': 'die Nachteile',
    'das Beispiel': 'die Beispiele',
    'die Erinnerung': 'die Erinnerungen',
    'das Handy': 'die Handys',
    'das Smartphone': 'die Smartphones',
    'der Computer': 'die Computer',
    'die E-Mail': 'die E-Mails',
    'die Nachricht': 'die Nachrichten',
    'die App': 'die Apps',
    'das Passwort': 'die Passwörter',
    'der Bildschirm': 'die Bildschirme',
    'die Datei': 'die Dateien',
    'das Hemd': 'die Hemden',
    'die Hose': 'die Hosen',
    'der Rock': 'die Röcke',
    'das Kleid': 'die Kleider',
    'die Jacke': 'die Jacken',
    'der Mantel': 'die Mäntel',
    'der Schuh': 'die Schuhe',
    'die Socke': 'die Socken',
    'der Hut': 'die Hüte',
    'die Mütze': 'die Mützen',
    'der Schal': 'die Schals',
    'der Stoff': 'die Stoffe',
    'der Pullover': 'die Pullover',
    'die Bluse': 'die Blusen',
    'das Ziel': 'die Ziele',
    'der Plan': 'die Pläne',
    'der Ingenieur': 'die Ingenieure',
    'der Anwalt': 'die Anwälte',
    'der Richter': 'die Richter',
    'der Architekt': 'die Architekten',
    'der Journalist': 'die Journalisten',
    'der Übersetzer': 'die Übersetzer',
    'der Verkäufer': 'die Verkäufer',
    'die Ärztin': 'die Ärztinnen',
    'die Ingenieurin': 'die Ingenieurinnen',
    'die Anwältin': 'die Anwältinnen',
    'die Richterin': 'die Richterinnen',
    'die Architektin': 'die Architektinnen',
    'die Journalistin': 'die Journalistinnen',
    'die Übersetzerin': 'die Übersetzerinnen',
    'die Verkäuferin': 'die Verkäuferinnen',
    'die Lehrerin': 'die Lehrerinnen',
    'die Speisekarte': 'die Speisekarten',
    'die Bestellung': 'die Bestellungen',
    'die Rechnung': 'die Rechnungen',
    'das Trinkgeld': 'die Trinkgelder',
    'der Kellner': 'die Kellner',
    'die Vorspeise': 'die Vorspeisen',
    'das Hauptgericht': 'die Hauptgerichte',
    'die Nachspeise': 'die Nachspeisen',
    'der Vorschlag': 'die Vorschläge',
    'der Schwager': 'die Schwäger',
    'die Schwägerin': 'die Schwägerinnen',
    'der Schwiegervater': 'die Schwiegerväter',
    'die Schwiegermutter': 'die Schwiegermütter',
    'der Enkel': 'die Enkel',
    'die Enkelin': 'die Enkelinnen',
    'der Neffe': 'die Neffen',
    'die Nichte': 'die Nichten',
    'der Nachbar': 'die Nachbarn',
    'der Prozess': 'die Prozesse',
    'die Anweisung': 'die Anweisungen',
    'die Anleitung': 'die Anleitungen',
    'der Wunsch': 'die Wünsche',
    'der Traum': 'die Träume',
    'die Bedingung': 'die Bedingungen',
    'die Möglichkeit': 'die Möglichkeiten',
    'die Beschwerde': 'die Beschwerden',
    'die Entschuldigung': 'die Entschuldigungen',
    'die Gelegenheit': 'die Gelegenheiten',
    'die Bedeutung': 'die Bedeutungen',
    'der Unterschied': 'die Unterschiede',
    'die Wirkung': 'die Wirkungen',
    'der Zusammenhang': 'die Zusammenhänge',
    'der Eindruck': 'die Eindrücke',
    'die Notwendigkeit': 'die Notwendigkeiten',
    'die Entwicklung': 'die Entwicklungen',
    'die Lösung': 'die Lösungen',
    'die Erfahrung': 'die Erfahrungen',
    'der Zweifel': 'die Zweifel',
    'die Bewerbung': 'die Bewerbungen',
    'das Anschreiben': 'die Anschreiben',
    'das Vorstellungsgespräch': 'die Vorstellungsgespräche',
    'die Stellenanzeige': 'die Stellenanzeigen',
    'der Arbeitgeber': 'die Arbeitgeber',
    'der Arbeitnehmer': 'die Arbeitnehmer',
    'der Arbeitsvertrag': 'die Arbeitsverträge',
    'die Probezeit': 'die Probezeiten',
    'die Kündigung': 'die Kündigungen',
    'die Zeitung': 'die Zeitungen',
    'die Zeitschrift': 'die Zeitschriften',
    'der Artikel': 'die Artikel',
    'die Sendung': 'die Sendungen',
    'die Meldung': 'die Meldungen',
    'die Schlagzeile': 'die Schlagzeilen',
    'die Stellungnahme': 'die Stellungnahmen',
    'die Anzeige': 'die Anzeigen',
    'die Überschrift': 'die Überschriften',
    'die Aufgabe': 'die Aufgaben',
    'der Absatz': 'die Absätze',
    'die Lücke': 'die Lücken',
    'die Zusammenfassung': 'die Zusammenfassungen',
    'der Hinweis': 'die Hinweise',
    'die Präsentation': 'die Präsentationen',
    'das Argument': 'die Argumente',
    'die Meinung': 'die Meinungen',
    'das Thema': 'die Themen',
    'das Ergebnis': 'die Ergebnisse',
    'die Einleitung': 'die Einleitungen',
    'der Schluss': 'die Schlüsse',
  },

  NO_PLURAL: [
    'die Eltern', 'der Käse', 'das Fleisch',
    'das Gemüse', 'das Obst', 'die Milch',
    'das Geld', 'der Kaffee', 'der Tee',
    'das Wasser', 'das Frühstück', 'die Freizeit',
    'der Sport', 'der Montag', 'der Dienstag',
    'der Mittwoch', 'der Donnerstag', 'der Freitag',
    'der Samstag', 'der Sonntag',
    'der Januar', 'der Februar',
    'der März', 'der April', 'der Mai',
    'der Juni', 'der Juli', 'der August',
    'der September', 'der Oktober', 'der November',
    'der Dezember', 'die Arbeit', 'der Urlaub',
    'die Post', 'das Fieber', 'die Schmerzen',
    'das Wetter', 'die Sonne', 'der Regen',
    'der Schnee', 'die Kindheit', 'die Jugend',
    'das Internet', 'die Kleidung', 'der Rat',
    'die Berufserfahrung', 'die Kenntnisse', 'die Werbung',
    'die Umwelt', 'der Klimawandel', 'der Müll',
    'die Energie', 'die Natur', 'die Verschmutzung',
  ],
};
